name: Visual Regression Tests
on:
  pull_request:
    types: [ready_for_review]
jobs:
  Percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10'
      - name: Install dependencies
        run: npm ci
      - name: Start storybook
        run: npm run build-storybook
      - name: Run Percy Tests
        run: npm run visreg-ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
